### ISSUE TITLE
QuickCheck Problem with Void Types?

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#1019]
There appears to a bug of somekind with quick check.  See the following excerpt from [this trace](https://github.com/Whiley/STD.wy/runs/1094451736?check_suite_focus=true):

```
Failure(RuntimeException, unknown type encountered (void)) type std::io::Reader ..... [1ms]
java.lang.RuntimeException: unknown type encountered (void)
	at wyc.cmd.QuickCheck.constructGenerator(QuickCheck.java:718)
	at wyc.cmd.QuickCheck.constructGenerator(QuickCheck.java:894)
	at wyc.cmd.QuickCheck.constructGenerator(QuickCheck.java:713)
	at wyc.cmd.QuickCheck.constructGenerator(QuickCheck.java:769)
	at wyc.cmd.QuickCheck.constructGenerator(QuickCheck.java:695)
	at wyc.cmd.QuickCheck.check(QuickCheck.java:529)
	at wyc.cmd.QuickCheck.check(QuickCheck.java:438)
	at wyc.cmd.QuickCheck.check(QuickCheck.java:413)
	at wyc.cmd.QuickCheck.check(QuickCheck.java:398)
	at wyc.cmd.QuickCheck.check(QuickCheck.java:388)
	at wyc.cmd.QuickCheck.execute(QuickCheck.java:318)
	at wycc.util.AbstractWorkspace$1$1.execute(AbstractWorkspace.java:127)
	at wycc.WyMain.main(WyMain.java:162)
```

**Comment by DavePearce** [comment]
This is the minimal test case:

```
public type Reader is {
    method close()
}

public function fn(Reader r) -> int:
    return 1
```
