### ISSUE TITLE
NullPointerException for Record Type Declaration

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#1047]
The following generates an exception:

```
type Tree is null | Node

type Node is ({ int data, Tree left, Tree right } n) where 
	// Data in nodes reachable from left must be below this
	(left is Node ==>  all { i in 0..10 | i < data })
```

Observe that removing `n` for the `Node` declaration and it's fine.  The trace is:

```
wyc: Exception in thread "main" java.lang.NullPointerException
        at wyil.check.FlowTypeUtils$Environment.getType(FlowTypeUtils.java:816)
        at wyil.check.FlowTypeCheck.pullVariable(FlowTypeCheck.java:2399)
        at wyil.check.FlowTypeCheck.pullExpression(FlowTypeCheck.java:1950)
        at wyil.check.FlowTypeCheck.pullRecordAccess(FlowTypeCheck.java:2343)
        at wyil.check.FlowTypeCheck.pullExpression(FlowTypeCheck.java:1999)
        at wyil.check.FlowTypeCheck.checkExpression(FlowTypeCheck.java:1313)
        at wyil.check.FlowTypeCheck.checkIs(FlowTypeCheck.java:1106)
        at wyil.check.FlowTypeCheck.checkCondition(FlowTypeCheck.java:964)
        at wyil.check.FlowTypeCheck.checkLogicalImplication(FlowTypeCheck.java:1083)
        at wyil.check.FlowTypeCheck.checkCondition(FlowTypeCheck.java:962)
        at wyil.check.FlowTypeCheck.checkConditions(FlowTypeCheck.java:877)
        at wyil.check.FlowTypeCheck.checkTypeDeclaration(FlowTypeCheck.java:239)
        at wyil.check.FlowTypeCheck.checkDeclaration(FlowTypeCheck.java:206)
        at wyil.check.FlowTypeCheck.checkUnit(FlowTypeCheck.java:223)
        at wyil.check.FlowTypeCheck.checkDeclaration(FlowTypeCheck.java:194)
        at wyil.check.FlowTypeCheck.check(FlowTypeCheck.java:182)
        at wyc.task.CompileTask.compile(CompileTask.java:143)
        at wyc.Compiler.run(Compiler.java:147)
        at wyc.Compiler.main(Compiler.java:195)
```

**Comment by DavePearce** [comment]
See also #937

**Comment by DavePearce** [comment]
Minimal example is this:

```Whiley
type Node is ({ int data } n) where data >= 0
```

Changing to `n.data` or removing `n` altogether and we're fine.
