### ISSUE TITLE
Complex types cause verifier to give cast exception.

### ISSUE THREAD

**Issue by utting** [Whiley/WhileyCompiler#561]
The attached sum0.txt program gives the following casting error after the loop invariant i >= 0 is added.

$ wyjc -verify -verbose sum0.whiley 
Parsed 1 source file(s). ....................................................... [51ms+2mb]
Typed 1 source file(s). ........................................................ [62ms+2mb]
Generated code for 1 source file(s). ............................................... [13ms]
[./sum0.whiley] applied definite assignment check ................................... [2ms]
[./sum0.whiley] applied module check ................................................ [1ms]
[./sum0.whiley] applied loop variants ............................................... [1ms]
[./sum0.whiley] applied coercion check .............................................. [1ms]
Whiley => Wyil: compiled 1 file(s) ............................................ [184ms-5mb]
Wyil => Wyal: compiled 1 file(s) ............................................... [31ms+1mb]
Wyil => Java: compiled 1 file(s) ................................................... [25ms]
Parsed 1 source file(s). ............................................................ [0ms]
Generated stubs for 1 source file(s). .......................................... [80ms+2mb]
internal failure (wycs.core.SemanticType$And cannot be cast to wycs.core.SemanticType$Array)
java.lang.ClassCastException: wycs.core.SemanticType$And cannot be cast to wycs.core.SemanticType$Array
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:311)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:225)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:344)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:215)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:398)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:217)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:500)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:223)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:344)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:215)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:459)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:221)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:186)
    at wycs.transforms.TypePropagation.propagate(TypePropagation.java:76)
    at wycs.transforms.TypePropagation.apply(TypePropagation.java:63)
    at wycs.builders.Wyal2WycsBuilder.build(Wyal2WycsBuilder.java:166)
    at wybs.util.StdBuildRule.apply(StdBuildRule.java:109)
    at wybs.util.StdProject.build(StdProject.java:256)
    at wyc.util.WycBuildTask.buildEntries(WycBuildTask.java:531)
    at wyc.util.WycBuildTask.build(WycBuildTask.java:499)
    at wyc.WycMain.run(WycMain.java:228)
    at wyjc.WyjcMain.main(WyjcMain.java:83)
[sum0.txt](https://github.com/Whiley/WhileyCompiler/files/78068/sum0.txt)

**Comment by utting** [comment]
The same problem arises without the loop invariant, once enough assertions are added to the program (see sum0b.txt).
The exception seems to happen because on line 311 of TypePropagation.java:

    src_type is !null&[int]

[sum0b.txt](https://github.com/Whiley/WhileyCompiler/files/78069/sum0b.txt)

**Comment by DavePearce** [comment]
A small test case in WyAL based on that Whiley program is:

<pre>
define invariant(null | [int] r0, int r1, int r2) is:
    r1 >= 0

assert "loop invariant not restored":
    forall (null | [int] values, int i$2):
        if:
            values is !(null)
        then:
            invariant(values, i$2 + 1, values[i$2])
</pre>

The essential problem is that the type being constructed for <code>values</code> in the <code>then</code> branch is <code>(null|int[])&!null</code>.  This should simplify down to <code>int[]</code>, but it is not simplified for reasons unknown at this point.  

This maybe related to #472.  Also, removing the redundant cast on line 311 doesn't fix the problem as it just reappears later on.  However, we should remove that redundant cast anyway.

**Comment by DavePearce** [comment]
This is still an issue.  However, this is now a WhileyTheoremProver issue.  See here:

https://github.com/Whiley/WhileyTheoremProver/issues/26
