### ISSUE TITLE
Cannot resolve as function or definition call with precondition

### ISSUE THREAD

**Issue by Aatch** [Whiley/WhileyCompiler#672]
Apologies if this is the wrong place to file this.

This code:

```
function swap(int x, int y) -> (int a, int b)
ensures y == b && x == a:
    return y, x
```

Causes this error:

```
./swap.whiley:0: cannot resolve as function or definition call
```

With verbose output, the backtrace is this:

```
wycc.lang.SyntaxError: cannot resolve as function or definition call
        at wycc.lang.SyntaxError.syntaxError(SyntaxError.java:341)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:560)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:223)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:344)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:215)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:459)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:221)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:186)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:76)
        at wycs.transforms.TypePropagation.apply(TypePropagation.java:63)
        at wycs.builders.Wyal2WycsBuilder.build(Wyal2WycsBuilder.java:166)
        at wybs.util.StdBuildRule.apply(StdBuildRule.java:109)
        at wybs.util.StdProject.build(StdProject.java:256)
        at wyc.util.WycBuildTask.buildEntries(WycBuildTask.java:518)
        at wyc.util.WycBuildTask.build(WycBuildTask.java:486)
        at wyc.WycMain.run(WycMain.java:228)
        at wyjc.WyjcMain.main(WyjcMain.java:83)
Caused by: wycc.util.ResolveError: no match for swap:swap_ensures_0((int,int,int))
        found: swap:swap_ensures_0 : (int,int,int,int)=>bool
        at wycs.builders.Wyal2WycsBuilder.selectCandidateFunctionOrMacro(Wyal2WycsBuilder.java:493)
        at wycs.builders.Wyal2WycsBuilder.resolveAsFunctionType(Wyal2WycsBuilder.java:429)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:540)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:223)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:344)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:215)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:459)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:221)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:186)
        at wycs.transforms.TypePropagation.propagate(TypePropagation.java:76)
        at wycs.transforms.TypePropagation.apply(TypePropagation.java:63)
        at wycs.builders.Wyal2WycsBuilder.build(Wyal2WycsBuilder.java:166)
        at wybs.util.StdBuildRule.apply(StdBuildRule.java:109)
        at wybs.util.StdProject.build(StdProject.java:256)
        at wyc.util.WycBuildTask.buildEntries(WycBuildTask.java:518)
        at wyc.util.WycBuildTask.build(WycBuildTask.java:486)
        at wyc.WycMain.run(WycMain.java:228)
        at wyjc.WyjcMain.main(WyjcMain.java:83)
```

Which I don't fully understand, however it appears to be related to the generated precondition checking function.

I am using `wyjc` from the WDK 0.3.40 downloaded from the website. The same error also appears with `wyc` however.

**Comment by Aatch** [comment]
This seems to happen with functions that return multiple values, as a function with no arguments, but three return values seems to also cause the same error. I think it's only looking at the first returned value and ignoring the rest when figuring out the appropriate signature for the verification function.

**Comment by DavePearce** [comment]
Yeah, this is a known problem with <code>v0.3.40</code>.  I've been making a lot of changes over the last few months, building up towards <code>v0.4.0</code> being fixed.

The last version which correctly handled multiple returns is <code>0.3.37</code>.  You can try it here http://whileylabs.com

**Comment by DavePearce** [comment]
I guess I should say that, for SWEN224, you should use <code>v0.3.37</code> for the assignments.
