### ISSUE TITLE
Verification Condition Generation and Function Constants

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#745]
The following minimal examples throws an exception in `VerificationConditionGenerator`:
```
constant table is [&f1]

function f1(int x) -> int:
    return x

type func is function(int)->int

method g(int d) -> func:
    return table[d]
```
The error message is:
```
wybs.lang.SyntaxError$InternalFailure: internal failure, unknown constant encountered (&FunctionRef_Valid_4:f1():function(int)->(int))
	at wyil.builders.VerificationConditionGenerator.convert(VerificationConditionGenerator.java:2387)
	at wyil.builders.VerificationConditionGenerator.convert(VerificationConditionGenerator.java:2371)
```
The problem seems to be translating lambda constants into WyAL.

**Comment by DavePearce** [comment]
Ok, have implemented a temporary fix by using the `translateAsUnknown` function.  This is fine for now, but in the future I may want a better way of representing unknown values.
