### ISSUE TITLE
Bug with Define Statement

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#875]
The following snippet fails:

```
package gif

type DAVE is int

define HELLO as "he"
```

With the following exception:

```
java.lang.NullPointerException
	at wybs.util.AbstractSyntacticItem.getAncestor(AbstractSyntacticItem.java:91)
	at wyc.task.CompileTask.build(CompileTask.java:198)
	at wyc.task.CompileTask.build(CompileTask.java:141)
	at wybs.util.StdBuildRule.apply(StdBuildRule.java:120)
	at wybs.util.StdProject.build(StdProject.java:169)
	at wycc.WyProject.build(WyProject.java:280)
	at wycc.commands.Build.execute(Build.java:158)
	at wycc.WyProject.execute(WyProject.java:245)
	at wycc.WyMain.execute(WyMain.java:307)
	at wycc.WyMain.main(WyMain.java:419)
```

**Comment by DavePearce** [comment]
This looks like its happening when the *parser* throws an exception.
