### ISSUE TITLE
Unknown Unit?

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#876]
The following snippet:

```
package gif

type DAVE is it
```

fails with the following exception:

```
java.lang.IllegalArgumentException: unknown unit
	at wyc.task.CompileTask.getWhileySourceFile(CompileTask.java:238)
	at wyc.task.CompileTask.build(CompileTask.java:200)
	at wyc.task.CompileTask.build(CompileTask.java:141)
	at wybs.util.StdBuildRule.apply(StdBuildRule.java:120)
	at wybs.util.StdProject.build(StdProject.java:169)
	at wycc.WyProject.build(WyProject.java:280)
	at wycc.commands.Build.execute(Build.java:158)
	at wycc.WyProject.execute(WyProject.java:245)
	at wycc.WyMain.execute(WyMain.java:307)
	at wycc.WyMain.main(WyMain.java:419)
```

**Comment by DavePearce** [comment]
This is definitely some kind of package issue, since taking it out of the `gif` package solves the problem.
