### ISSUE TITLE
Unresolved Types in Function/Method Stub

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#877]
The following minimal example:

```
package lz77

/**
 * A simplistic implementation of the Lempel-Ziv 77 decompression.
 *
 * See: http://en.wikipedia.org/wiki/LZ77_and_LZ78
 */
import std::integer

// Decompress the given compressed bytestream.  This is done in a
// relatively naive fashion, whereby the entire generated stream is kept
// in memory.  In practice, only the sliding window needs to be kept in
// memory.
function decompress(byte[] data) -> int:
    return integer::toUnsignedInt(0b001)
```

Generates the following error:

```
ava.lang.ClassCastException: wyil.lang.WyilFile$Decl$Unknown cannot be cast to wyil.lang.WyilFile$Decl$Type
	at wyil.lang.WyilFile$Type$Nominal.getDeclaration(WyilFile.java:4369)
	at wyil.transform.RecursiveTypeAnalysis.visitTypeNominal(RecursiveTypeAnalysis.java:106)
	at wyil.transform.RecursiveTypeAnalysis.visitTypeNominal(RecursiveTypeAnalysis.java:1)
	at wyil.util.AbstractConsumer.visitType(AbstractConsumer.java:771)
	at wyil.util.AbstractConsumer.visitVariable(AbstractConsumer.java:91)
	at wyil.util.AbstractConsumer.visitVariables(AbstractConsumer.java:86)
	at wyil.util.AbstractConsumer.visitFunction(AbstractConsumer.java:144)
        ....
```

**Comment by DavePearce** [comment]
This seems to be something to do with calling a function in another library, as the following also causes the same problem:

```
import std::ascii
import std::integer


function decompress() -> ascii::string:
    return integer::toString(0b001)
```

**Comment by DavePearce** [comment]
**UPDATE:** I think the problem is that the type `ascii::string` on the stub created for `decompress` is not resolved.

**Comment by DavePearce** [comment]
**UPDATE:** even this program causes the problem:

```
import string from std::ascii
import std::integer

function decompress() -> string:
    return ""
```

**Comment by DavePearce** [comment]
**UPDATE:** the problem must be related to allocating `Ref` instances which don't force the allocation of their targets?

**Comment by DavePearce** [comment]
Ok, the issue is that the importer wasn't generating patches correctly.
