### ISSUE TITLE
Build Run Command Failing

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#878]
Currently, command `wy run` is not working.  Details:

`src/main.whiley`:
```
import std::io

public method main():    
    io::println("Hello World")
```

`wy.toml`:
```
[package]
name="test"
authors=["David J. Pearce"]
version="0.1.0"

[build]
main="main::main"

[dependencies]
std="0.2.6"
```

The error being reported is:
```
bash-3.2$ wy run

Unable to read configuration file /Users/djp/.whiley/wy.toml
TARGET: main/main
java.lang.NullPointerException
	at wyil.interpreter.Interpreter$CallStack.getCallable(Interpreter.java:1369)
	at wyil.interpreter.Interpreter.execute(Interpreter.java:83)
	at wyc.Activator$1.execute(Activator.java:145)
	at wycc.commands.Run.execute(Run.java:132)
	at wycc.WyProject.execute(WyProject.java:245)
	at wycc.WyMain.execute(WyMain.java:307)
	at wycc.WyMain.main(WyMain.java:419)
```

**Comment by DavePearce** [comment]
Problem may be in `wyc.Activator`:

```
Interpreter interpreter = new Interpreter(System.out);
			// Create the initial stack
			Interpreter.CallStack stack = interpreter.new CallStack();
			// FIXME: load relevant modules
```

The call stack needs to be initialised with some callables.
