### ISSUE TITLE
Bug with NameResolution?

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#927]
The following example raises a `NullPointerException`:

```
import Vector from std::vector
import unique_elements from std::array

// Array set is vector where all visible elements unique
type ArraySet<T> is (Vector<T> v)
// All elements up to length are unique
where unique_elements<T>(v.items,v.length)
```

The exception is something like this:

```
Caused by: java.lang.NullPointerException
	at wyil.transform.SymbolTable$AbstractGroup.isAvailable(SymbolTable.java:239)
	at wyil.transform.SymbolTable$ExternalGroup.isAvailable(SymbolTable.java:1)
	at wyil.transform.SymbolTable.isAvailable(SymbolTable.java:121)
	at wyil.transform.NameResolution$Patch.imPort(NameResolution.java:362)
	at wyil.transform.NameResolution$Patch.apply(NameResolution.java:355)
	at wyil.transform.NameResolution.apply(NameResolution.java:112)
	at wyc.task.CompileTask.execute(CompileTask.java:191)
	at wyc.task.CompileTask.lambda$0(CompileTask.java:159)
```

**Comment by DavePearce** [comment]
This is also arising in another case which seems to be related.  Specifically, when building `HTML.wy` we get a similar error to the above.  At this time, I cannot find a work around.

**Comment by DavePearce** [comment]
**UPDATE** at a guess the original problem is related to importing properties.  That is, the method `NameResolution.allocateStub()` does not support properties at this time!!

**Comment by DavePearce** [comment]
Split into #931 and #932
